channels:
- conda-forge
dependencies:
- python=3.10.14
- pip<=24.2
- pip:
  - torch==2.2.2
  - torchvision==0.17.2
  - transformers==4.44.0
  - mlflow==2.14.3
  - accelerate==0.33.0
  - bitsandbytes==0.43.3
  - cffi==1.17.0
  - dill==0.3.8
  - flash-attn==2.5.5
  - google-api-core==2.19.2
  - jaraco-context==5.3.0
  - jaraco-functools==4.0.1
  - jaraco-text==3.12.1
  - more-itertools==10.3.0
  - numpy==1.23.5
  - nvidia-ml-py==12.560.30
  - onnxruntime-training==1.18.0
  - onnxruntime==1.17.3
  - ordered-set==4.1.0
  - packaging==24.1
  - pandas==2.2.2
  - protobuf==3.20.3
  - pynvml==11.5.3
  - pyyaml==6.0.2
  - requests==2.32.3
  - scikit-learn==1.5.2
  - scipy==1.14.0
  - sentencepiece==0.1.99
name: mlflow-env
